/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_dustsimulation_free: (a: number, b: number) => void;
export const __wbg_noisegenerator_free: (a: number, b: number) => void;
export const dustsimulation_get_colors_ptr: (a: number) => number;
export const dustsimulation_get_matrices_ptr: (a: number) => number;
export const dustsimulation_get_particles_ptr: (a: number) => number;
export const dustsimulation_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number, t: number, u: number) => number;
export const dustsimulation_update: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number, t: number, u: number, v: number, w: number, x: number, y: number, z: number, a1: number, b1: number, c1: number, d1: number, e1: number, f1: number, g1: number, h1: number) => void;
export const noisegenerator_fill_2d_noise: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => void;
export const noisegenerator_fill_3d_noise: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number) => void;
export const noisegenerator_get_buffer_len: (a: number) => number;
export const noisegenerator_new: (a: number) => number;
export const noisegenerator_get_buffer_ptr: (a: number) => number;
export const __wbg_cubesimulation_free: (a: number, b: number) => void;
export const __wbg_get_cubesimulation_burst: (a: number) => number;
export const __wbg_get_cubesimulation_flight_envelope: (a: number) => number;
export const __wbg_get_cubesimulation_flight_swirl: (a: number) => number;
export const __wbg_get_cubesimulation_rotation_x: (a: number) => number;
export const __wbg_get_cubesimulation_rotation_y: (a: number) => number;
export const __wbg_get_cubesimulation_velocity_x: (a: number) => number;
export const __wbg_get_cubesimulation_velocity_y: (a: number) => number;
export const __wbg_set_cubesimulation_burst: (a: number, b: number) => void;
export const __wbg_set_cubesimulation_flight_envelope: (a: number, b: number) => void;
export const __wbg_set_cubesimulation_flight_swirl: (a: number, b: number) => void;
export const __wbg_set_cubesimulation_rotation_x: (a: number, b: number) => void;
export const __wbg_set_cubesimulation_rotation_y: (a: number, b: number) => void;
export const __wbg_set_cubesimulation_velocity_x: (a: number, b: number) => void;
export const __wbg_set_cubesimulation_velocity_y: (a: number, b: number) => void;
export const __wbg_starsimulation_free: (a: number, b: number) => void;
export const cubesimulation_get_face_matrices_ptr: (a: number) => number;
export const cubesimulation_get_face_opacities_ptr: (a: number) => number;
export const cubesimulation_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => number;
export const cubesimulation_update: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number) => void;
export const starsimulation_get_matrices_ptr: (a: number) => number;
export const starsimulation_new: (a: number, b: number) => number;
export const starsimulation_update: (a: number, b: number, c: number, d: number) => void;
export const starsimulation_get_positions_ptr: (a: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_start: () => void;
